 /******************************************************************************
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Source file for TM4C123GH6PM Microcontroller - Port Driver.
 *
 ******************************************************************************/

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION           (1U)
#define PORT_PBCFG_SW_MINOR_VERSION           (0U)
#define PORT_PBCFG_SW_PATCH_VERSION           (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION   (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION   (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION   (3U)

#include "Port.h"

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration = {
		PORTA , PIN0_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTA , PIN1_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTA , PIN2_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTA , PIN3_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTA , PIN4_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTA , PIN5_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTA , PIN6_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTA , PIN7_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,

		PORTB , PIN0_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTB , PIN1_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTB , PIN2_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTB , PIN3_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTB , PIN4_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTB , PIN5_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTB , PIN6_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTB , PIN7_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,

		PORTC , PIN0_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTC , PIN1_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTC , PIN2_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTC , PIN3_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTC , PIN4_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTC , PIN5_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTC , PIN6_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTC , PIN7_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,

		PORTD , PIN0_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTD , PIN1_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTD , PIN2_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTD , PIN3_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTD , PIN4_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTD , PIN5_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTD , PIN6_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTD , PIN7_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,

		PORTE , PIN0_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTE , PIN1_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTE , PIN2_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTE , PIN3_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTE , PIN4_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTE , PIN5_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTE , PIN6_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTE , PIN7_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,

		PORTF , PIN0_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTF , PIN1_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTF , PIN2_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTF , PIN3_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORTF , PIN4_INDEX, PORT_PIN_IN, OFF, STD_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
};